### ISSUE TITLE
Training on multiple gpus get errors

### ISSUE THREAD

**Issue by Jack-lx-jiang** [Haichao-Zhang/FeatureScatter#1]
Hi,
I change the `CUDA_VISIBLE_DEVICES=0` to `CUDA_VISIBLE_DEVICES='0,1,2,3'` in 'fs_train.sh'
and then got the error message below.
```
/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "fs_main.py", line 324, in <module>
    train_fun(epoch, net)
  File "fs_main.py", line 275, in train_fun
    outputs, loss_fs, flag_out, _, _ = net(inputs.detach(), targets)
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/jlx/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration
```
if anyone should ever have time to answer: thanks in advance for trying to help me out.

**Comment by Haichao-Zhang** [comment]
Hi, you can pull the latest code and it should work for multi-gpu training. 
Close it for now and feel free to reopen it if you have any further issues.

**Comment by feather0011** [comment]
Hello. 

I think I have some related issue.

When I try to run the code in multiple GPU, I got error message below.
(line index maybe different because I added some comment)

```  
0% 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "fs_main.py", line 339, in <module>
    train_fun(epoch, net)
  File "fs_main.py", line 291, in train_fun
    outputs, adv_loss = net(inputs.detach(), targets)
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/jwhwang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jwhwang/FeatureScatter/attack_methods.py", line 346, in forward
    aux_net = pickle.loads(pickle.dumps(self.basic_net))
AttributeError: Can't pickle local object 'Module._replicate_for_data_parallel.<locals>.zero_grad'
```

Beside, can you explain me what is `aux_net = pickle.loads(pickle.dumps(self.basic_net))` for (especially for whitebox)?
 
I understand that aux_net is a network to generate adversarial example (and I wonder shouldn't it be aux_net = pickle.loads(pickle.dumps(**self.attack_net**)) for black box attack), but I don't know why you convert network object to string and re-convert it to network object. Is it for deep copy? But for what?
